baseURL = "http://example.org/"

# Change the default theme to be use when building the site with Hugo
# theme = "LoveIt"

# website title
title = "Laura del Río Martín"

# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "en-us"
# language name ["English", "简体中文", "Français", "Polski", ...]
languageName = "English"

# Author config
#[author]
#  name = "Laura del Río Martín"
#  email = "laura.del.rio.martin@gmail.com"
#  link = ""

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "home"
    pre = ""
    post = ""
    name = "Home"
    url = "/home/"
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "publications"
    pre = ""
    post = ""
    name = "Publications"
    url = "/publications/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "teaching"
    pre = ""
    post = ""
    name = "Teaching"
    url = "/teaching/"
    title = "Teaching"
  [[menu.main]]
    weight = 4
    identifier = "fundings"
    pre = ""
    post = ""
    name = "Fundings"
    url = "/funding/"
    title = "Fundraising and research projects"
  [[menu.main]]
    weight = 5
    identifier = "contact"
    pre = ""
    post = ""
    name = "Contact"
    url = "/contact/"
    title = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true	
[math]
enable = true

  
